### ISSUE TITLE
Update macOS softwareupdate Ignore List.sh

### ISSUE THREAD

**Issue by mani2care** [palantir/jamf-pro-scripts#28]
Hi is there any solution for ignoring the monterey on big sur M1 devices 

restriction i can able to made But i  want to remove from system preference @monterey OS

**Comment by mpanighetti** [comment]
Unfortunately, the ability to ignore software updates via command line (I assume you're referring to [this script](https://github.com/palantir/jamf-pro-scripts/blob/main/scripts/Update%20macOS%20softwareupdate%20Ignore%20List.sh)) was removed in macOS Big Sur. Restricting major macOS releases via your MDM would be your only remaining option, but there's a maximum deferral period of 90 days and it's been longer than that since Monterey was released.

Recommend reaching out to the Mac admin community for other potential solutions ([the Slack team is great](https://www.macadmins.org)). Hope that helps!
